version: "3.7"

services:
    # image project
    estudo_api:
        container_name: estudo_api_laravel-9
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - api
    
    # nginx
    nginx:
        container_name: estudo_api_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8004:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - api

    # db mysql
    mysql:
        container_name: estudo_api_mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3321:3306"
        networks: 
            - api

    # queue
    queue:
        container_name: estudo_api_queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - estudo_api
        networks: 
            - api

    # redis
    redis:
        container_name: estudo_api_redis
        image: redis:latest
        networks: 
            - api
        ports:
            - 6361:6379

networks: 
    api:
        driver: bridge